# Generated by Django 4.0.5 on 2022-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.IntegerField()),
                ('order_number', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('price_rub', models.FloatField()),
                ('date_of_supply', models.DateField()),
                ('removed', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
            ],
        ),
    ]
